export const red = "red-input";
export const green = "green-input";
export const blue = "blue-input";
export const boxstr = "box";
export const boxstr2 = "box2";
export const inputstr = "input";
export const br = "<br>";
export const div = "div";
export const img = "img";
export const col = "col";
export const btn = "btn";
export const button = "button";
export const rowstr = "row";
export const btnStrt = "btn-start";
export const btnDanger = "btn-danger";
export const btnSuccess = "bg-success";
export const btnWarn = "btn-warning";
export const btntodo = "btn-add-todo";
export const pointer = "pointer";
export const click = "click";
export const addbtn = "addbtn";
export const nameitem = "name-item";
export const animalShow = "animal-show-case";
export const animalChosen = "chosen-animal";
export const animalChosenImg = "#animal-show-case img";
export const tododesc = "todo-description";
export const tasks = "tasks";
export const editIcon = `Edit: <i class="bi bi-pencil-square"></i>`;
export const deleteIcon = `Delete: <i class="bi bi-trash3-fill"></i>`;
export const successIcon = 'Success:<i class="bi bi-calendar-check-fill"></i>';
export const desc = "description";
